/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedSignUpRouteImport } from './routes/_unauthenticated/sign-up'
import { Route as UnauthenticatedSignInRouteImport } from './routes/_unauthenticated/sign-in'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedAreaSlugRouteRouteImport } from './routes/_authenticated/$areaSlug/route'
import { Route as AuthenticatedAreaSlugIndexRouteImport } from './routes/_authenticated/$areaSlug/index'
import { Route as AuthenticatedAreaSlugThreadSlugRouteImport } from './routes/_authenticated/$areaSlug/$threadSlug'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UnauthenticatedSignUpRoute = UnauthenticatedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const UnauthenticatedSignInRoute = UnauthenticatedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreaSlugRouteRoute =
  AuthenticatedAreaSlugRouteRouteImport.update({
    id: '/$areaSlug',
    path: '/$areaSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugIndexRoute =
  AuthenticatedAreaSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAreaSlugRouteRoute,
  } as any)
const AuthenticatedAreaSlugThreadSlugRoute =
  AuthenticatedAreaSlugThreadSlugRouteImport.update({
    id: '/$threadSlug',
    path: '/$threadSlug',
    getParentRoute: () => AuthenticatedAreaSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$areaSlug': typeof AuthenticatedAreaSlugRouteRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/sign-up': typeof UnauthenticatedSignUpRoute
  '/$areaSlug/$threadSlug': typeof AuthenticatedAreaSlugThreadSlugRoute
  '/$areaSlug/': typeof AuthenticatedAreaSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/sign-up': typeof UnauthenticatedSignUpRoute
  '/$areaSlug/$threadSlug': typeof AuthenticatedAreaSlugThreadSlugRoute
  '/$areaSlug': typeof AuthenticatedAreaSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_authenticated/$areaSlug': typeof AuthenticatedAreaSlugRouteRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_unauthenticated/sign-in': typeof UnauthenticatedSignInRoute
  '/_unauthenticated/sign-up': typeof UnauthenticatedSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$areaSlug/$threadSlug': typeof AuthenticatedAreaSlugThreadSlugRoute
  '/_authenticated/$areaSlug/': typeof AuthenticatedAreaSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$areaSlug'
    | '/inbox'
    | '/sign-in'
    | '/sign-up'
    | '/$areaSlug/$threadSlug'
    | '/$areaSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/sign-in'
    | '/sign-up'
    | '/$areaSlug/$threadSlug'
    | '/$areaSlug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/$areaSlug'
    | '/_authenticated/inbox'
    | '/_unauthenticated/sign-in'
    | '/_unauthenticated/sign-up'
    | '/_authenticated/'
    | '/_authenticated/$areaSlug/$threadSlug'
    | '/_authenticated/$areaSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_unauthenticated/sign-up': {
      id: '/_unauthenticated/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthenticatedSignUpRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/sign-in': {
      id: '/_unauthenticated/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthenticatedSignInRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$areaSlug': {
      id: '/_authenticated/$areaSlug'
      path: '/$areaSlug'
      fullPath: '/$areaSlug'
      preLoaderRoute: typeof AuthenticatedAreaSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$areaSlug/': {
      id: '/_authenticated/$areaSlug/'
      path: '/'
      fullPath: '/$areaSlug/'
      preLoaderRoute: typeof AuthenticatedAreaSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAreaSlugRouteRoute
    }
    '/_authenticated/$areaSlug/$threadSlug': {
      id: '/_authenticated/$areaSlug/$threadSlug'
      path: '/$threadSlug'
      fullPath: '/$areaSlug/$threadSlug'
      preLoaderRoute: typeof AuthenticatedAreaSlugThreadSlugRouteImport
      parentRoute: typeof AuthenticatedAreaSlugRouteRoute
    }
  }
}

interface AuthenticatedAreaSlugRouteRouteChildren {
  AuthenticatedAreaSlugThreadSlugRoute: typeof AuthenticatedAreaSlugThreadSlugRoute
  AuthenticatedAreaSlugIndexRoute: typeof AuthenticatedAreaSlugIndexRoute
}

const AuthenticatedAreaSlugRouteRouteChildren: AuthenticatedAreaSlugRouteRouteChildren =
  {
    AuthenticatedAreaSlugThreadSlugRoute: AuthenticatedAreaSlugThreadSlugRoute,
    AuthenticatedAreaSlugIndexRoute: AuthenticatedAreaSlugIndexRoute,
  }

const AuthenticatedAreaSlugRouteRouteWithChildren =
  AuthenticatedAreaSlugRouteRoute._addFileChildren(
    AuthenticatedAreaSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreaSlugRouteRoute: typeof AuthenticatedAreaSlugRouteRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreaSlugRouteRoute: AuthenticatedAreaSlugRouteRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedSignInRoute: typeof UnauthenticatedSignInRoute
  UnauthenticatedSignUpRoute: typeof UnauthenticatedSignUpRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedSignInRoute: UnauthenticatedSignInRoute,
  UnauthenticatedSignUpRoute: UnauthenticatedSignUpRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
